# Form implementation generated from reading ui file 'osint_app.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 912)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.centralwidget_2.setGeometry(QtCore.QRect(0, 0, 779, 910))
        self.centralwidget_2.setObjectName("centralwidget_2")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget_2)
        self.mainLayout.setContentsMargins(28, 28, 28, 20)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setSpacing(16)
        self.headerLayout.setObjectName("headerLayout")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget_2)
        self.label_title.setStyleSheet("font-size: 20pt;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"letter-spacing: 0.8px;")
        self.label_title.setObjectName("label_title")
        self.headerLayout.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.comboLanguage = QtWidgets.QComboBox(parent=self.centralwidget_2)
        self.comboLanguage.setMinimumSize(QtCore.QSize(154, 36))
        self.comboLanguage.setStyleSheet("QComboBox {\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    min-width: 120px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 24px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 6px solid #999999;\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    selection-background-color: #2a2a2a;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}")
        self.comboLanguage.setObjectName("comboLanguage")
        self.comboLanguage.addItem("")
        self.comboLanguage.addItem("")
        self.headerLayout.addWidget(self.comboLanguage)
        self.mainLayout.addLayout(self.headerLayout)
        self.frame_disclaimer = QtWidgets.QFrame(parent=self.centralwidget_2)
        self.frame_disclaimer.setStyleSheet("QFrame {\n"
"    background-color: rgba(26, 26, 26, 0.8);\n"
"    border-left: 3px solid #666666;\n"
"    border-radius: 0;\n"
"    padding: 14px 20px;\n"
"}")
        self.frame_disclaimer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_disclaimer.setObjectName("frame_disclaimer")
        self.disclaimerLayout = QtWidgets.QHBoxLayout(self.frame_disclaimer)
        self.disclaimerLayout.setContentsMargins(0, 0, 0, 0)
        self.disclaimerLayout.setSpacing(12)
        self.disclaimerLayout.setObjectName("disclaimerLayout")
        self.label_legal = QtWidgets.QLabel(parent=self.frame_disclaimer)
        self.label_legal.setStyleSheet("color: #aaaaaa;\n"
"font-size: 10pt;\n"
"font-weight: 500;\n"
"line-height: 1.4;")
        self.label_legal.setWordWrap(True)
        self.label_legal.setObjectName("label_legal")
        self.disclaimerLayout.addWidget(self.label_legal)
        self.mainLayout.addWidget(self.frame_disclaimer)
        self.label_instrucciones = QtWidgets.QLabel(parent=self.centralwidget_2)
        self.label_instrucciones.setStyleSheet("font-size: 12pt;\n"
"color: #cccccc;\n"
"font-weight: 500;\n"
"padding: 8px 0 4px 0;")
        self.label_instrucciones.setObjectName("label_instrucciones")
        self.mainLayout.addWidget(self.label_instrucciones)
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setSpacing(10)
        self.inputLayout.setObjectName("inputLayout")
        self.entrada_dominio = QtWidgets.QLineEdit(parent=self.centralwidget_2)
        self.entrada_dominio.setMinimumSize(QtCore.QSize(0, 48))
        self.entrada_dominio.setStyleSheet("QLineEdit {\n"
"    font-size: 12pt;\n"
"    padding: 14px 18px;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    selection-background-color: #3a3a3a;\n"
"    font-weight: 500;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #4a4a4a;\n"
"    background-color: #1f1f1f;\n"
"    outline: none;\n"
"}")
        self.entrada_dominio.setObjectName("entrada_dominio")
        self.inputLayout.addWidget(self.entrada_dominio)
        self.btn_history = QtWidgets.QPushButton(parent=self.centralwidget_2)
        self.btn_history.setMinimumSize(QtCore.QSize(48, 48))
        self.btn_history.setMaximumSize(QtCore.QSize(48, 48))
        self.btn_history.setStyleSheet("QPushButton {\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    font-size: 16pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}")
        self.btn_history.setObjectName("btn_history")
        self.inputLayout.addWidget(self.btn_history)
        self.mainLayout.addLayout(self.inputLayout)
        self.riskIndicatorLayout = QtWidgets.QHBoxLayout()
        self.riskIndicatorLayout.setSpacing(14)
        self.riskIndicatorLayout.setObjectName("riskIndicatorLayout")
        self.label_risk = QtWidgets.QLabel(parent=self.centralwidget_2)
        self.label_risk.setStyleSheet("font-size: 11pt;\n"
"color: #999999;\n"
"font-weight: 500;")
        self.label_risk.setObjectName("label_risk")
        self.riskIndicatorLayout.addWidget(self.label_risk)
        self.riskIndicator = QtWidgets.QFrame(parent=self.centralwidget_2)
        self.riskIndicator.setMinimumSize(QtCore.QSize(180, 8))
        self.riskIndicator.setMaximumSize(QtCore.QSize(180, 8))
        self.riskIndicator.setStyleSheet("QFrame {\n"
"    background-color: #4a4a4a;\n"
"    border-radius: 4px;\n"
"}")
        self.riskIndicator.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.riskIndicator.setObjectName("riskIndicator")
        self.riskIndicatorLayout.addWidget(self.riskIndicator)
        self.label_risk_text = QtWidgets.QLabel(parent=self.centralwidget_2)
        self.label_risk_text.setStyleSheet("font-size: 11pt;\n"
"font-weight: 600;\n"
"color: #4a4a4a;")
        self.label_risk_text.setObjectName("label_risk_text")
        self.riskIndicatorLayout.addWidget(self.label_risk_text)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.riskIndicatorLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.riskIndicatorLayout)
        self.frame_tools = QtWidgets.QFrame(parent=self.centralwidget_2)
        self.frame_tools.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"}")
        self.frame_tools.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_tools.setObjectName("frame_tools")
        self.toolsLayout = QtWidgets.QVBoxLayout(self.frame_tools)
        self.toolsLayout.setContentsMargins(0, 0, 0, 0)
        self.toolsLayout.setSpacing(12)
        self.toolsLayout.setObjectName("toolsLayout")
        self.toolsGrid = QtWidgets.QGridLayout()
        self.toolsGrid.setSpacing(10)
        self.toolsGrid.setObjectName("toolsGrid")
        self.btn_geo = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_geo.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_geo.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_geo.setObjectName("btn_geo")
        self.toolsGrid.addWidget(self.btn_geo, 0, 0, 1, 1)
        self.btn_whois = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_whois.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_whois.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_whois.setObjectName("btn_whois")
        self.toolsGrid.addWidget(self.btn_whois, 0, 1, 1, 1)
        self.btn_ping = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_ping.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_ping.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_ping.setObjectName("btn_ping")
        self.toolsGrid.addWidget(self.btn_ping, 0, 2, 1, 1)
        self.btn_dns = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_dns.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_dns.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_dns.setObjectName("btn_dns")
        self.toolsGrid.addWidget(self.btn_dns, 0, 3, 1, 1)
        self.btn_ssl = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_ssl.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_ssl.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_ssl.setObjectName("btn_ssl")
        self.toolsGrid.addWidget(self.btn_ssl, 1, 0, 1, 1)
        self.btn_headers = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_headers.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_headers.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_headers.setObjectName("btn_headers")
        self.toolsGrid.addWidget(self.btn_headers, 1, 1, 1, 1)
        self.btn_portscan = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_portscan.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_portscan.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_portscan.setObjectName("btn_portscan")
        self.toolsGrid.addWidget(self.btn_portscan, 1, 2, 1, 1)
        self.btn_reverse = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_reverse.setMinimumSize(QtCore.QSize(0, 46))
        self.btn_reverse.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 18px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_reverse.setObjectName("btn_reverse")
        self.toolsGrid.addWidget(self.btn_reverse, 1, 3, 1, 1)
        self.toolsLayout.addLayout(self.toolsGrid)
        self.actionButtonsLayout = QtWidgets.QHBoxLayout()
        self.actionButtonsLayout.setSpacing(12)
        self.actionButtonsLayout.setObjectName("actionButtonsLayout")
        self.btn_quick = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_quick.setMinimumSize(QtCore.QSize(0, 44))
        self.btn_quick.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    padding: 12px 20px;\n"
"    background-color: #e8e8e8;\n"
"    color: #0f0f0f;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #cccccc;\n"
"}")
        self.btn_quick.setObjectName("btn_quick")
        self.actionButtonsLayout.addWidget(self.btn_quick)
        self.btn_export = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_export.setMinimumSize(QtCore.QSize(130, 44))
        self.btn_export.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 20px;\n"
"    background-color: #1a1a1a;\n"
"    color: #e8e8e8;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_export.setObjectName("btn_export")
        self.actionButtonsLayout.addWidget(self.btn_export)
        self.btn_clear = QtWidgets.QPushButton(parent=self.frame_tools)
        self.btn_clear.setMinimumSize(QtCore.QSize(130, 44))
        self.btn_clear.setStyleSheet("QPushButton {\n"
"    font-size: 11pt;\n"
"    font-weight: 500;\n"
"    padding: 12px 20px;\n"
"    background-color: #1a1a1a;\n"
"    color: #999999;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    color: #e8e8e8;\n"
"    border-color: #3a3a3a;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0f0f0f;\n"
"}")
        self.btn_clear.setObjectName("btn_clear")
        self.actionButtonsLayout.addWidget(self.btn_clear)
        self.toolsLayout.addLayout(self.actionButtonsLayout)
        self.mainLayout.addWidget(self.frame_tools)
        self.frame_results = QtWidgets.QFrame(parent=self.centralwidget_2)
        self.frame_results.setMinimumSize(QtCore.QSize(0, 320))
        self.frame_results.setStyleSheet("QFrame {\n"
"    background-color: #1a1a1a;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 8px;\n"
"}")
        self.frame_results.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_results.setObjectName("frame_results")
        self.resultsLayout = QtWidgets.QVBoxLayout(self.frame_results)
        self.resultsLayout.setContentsMargins(0, 0, 0, 0)
        self.resultsLayout.setSpacing(0)
        self.resultsLayout.setObjectName("resultsLayout")
        self.resultsHeader = QtWidgets.QHBoxLayout()
        self.resultsHeader.setContentsMargins(20, 16, 20, 16)
        self.resultsHeader.setSpacing(14)
        self.resultsHeader.setObjectName("resultsHeader")
        self.label_results = QtWidgets.QLabel(parent=self.frame_results)
        self.label_results.setStyleSheet("font-size: 12pt;\n"
"font-weight: 600;\n"
"color: #e8e8e8;")
        self.label_results.setObjectName("label_results")
        self.resultsHeader.addWidget(self.label_results)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.resultsHeader.addItem(spacerItem2)
        self.btn_copy = QtWidgets.QPushButton(parent=self.frame_results)
        self.btn_copy.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_copy.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_copy.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #999999;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 6px;\n"
"    font-size: 12pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    color: #e8e8e8;\n"
"}")
        self.btn_copy.setObjectName("btn_copy")
        self.resultsHeader.addWidget(self.btn_copy)
        self.btn_clear_results = QtWidgets.QPushButton(parent=self.frame_results)
        self.btn_clear_results.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_clear_results.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_clear_results.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #999999;\n"
"    border: 1px solid #2a2a2a;\n"
"    border-radius: 6px;\n"
"    font-size: 14pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2a2a2a;\n"
"    color: #e8e8e8;\n"
"}")
        self.btn_clear_results.setObjectName("btn_clear_results")
        self.resultsHeader.addWidget(self.btn_clear_results)
        self.resultsLayout.addLayout(self.resultsHeader)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_results)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-top: 1px solid #2a2a2a;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: transparent;\n"
"    color: #999999;\n"
"    padding: 12px 20px;\n"
"    border: none;\n"
"    border-bottom: 2px solid transparent;\n"
"    font-weight: 500;\n"
"    font-size: 10pt;\n"
"    min-width: 100px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    color: #e8e8e8;\n"
"    border-bottom: 2px solid #e8e8e8;\n"
"    font-weight: 600;\n"
"}\n"
"QTabBar::tab:hover {\n"
"    color: #cccccc;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_geo = QtWidgets.QWidget()
        self.tab_geo.setObjectName("tab_geo")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_geo)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.text_geo = QtWidgets.QTextEdit(parent=self.tab_geo)
        self.text_geo.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_geo.setReadOnly(True)
        self.text_geo.setObjectName("text_geo")
        self.verticalLayout_5.addWidget(self.text_geo)
        self.tabWidget.addTab(self.tab_geo, "")
        self.tab_whois = QtWidgets.QWidget()
        self.tab_whois.setObjectName("tab_whois")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_whois)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.text_whois = QtWidgets.QTextEdit(parent=self.tab_whois)
        self.text_whois.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_whois.setReadOnly(True)
        self.text_whois.setObjectName("text_whois")
        self.verticalLayout_6.addWidget(self.text_whois)
        self.tabWidget.addTab(self.tab_whois, "")
        self.tab_ping = QtWidgets.QWidget()
        self.tab_ping.setObjectName("tab_ping")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_ping)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.text_ping = QtWidgets.QTextEdit(parent=self.tab_ping)
        self.text_ping.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_ping.setReadOnly(True)
        self.text_ping.setObjectName("text_ping")
        self.gridLayout.addWidget(self.text_ping, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_ping, "")
        self.tab_dns = QtWidgets.QWidget()
        self.tab_dns.setObjectName("tab_dns")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_dns)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.text_dns = QtWidgets.QTextEdit(parent=self.tab_dns)
        self.text_dns.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_dns.setReadOnly(True)
        self.text_dns.setObjectName("text_dns")
        self.verticalLayout_8.addWidget(self.text_dns)
        self.tabWidget.addTab(self.tab_dns, "")
        self.tab_ssl = QtWidgets.QWidget()
        self.tab_ssl.setObjectName("tab_ssl")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_ssl)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.text_ssl = QtWidgets.QTextEdit(parent=self.tab_ssl)
        self.text_ssl.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_ssl.setReadOnly(True)
        self.text_ssl.setObjectName("text_ssl")
        self.verticalLayout_9.addWidget(self.text_ssl)
        self.tabWidget.addTab(self.tab_ssl, "")
        self.tab_headers = QtWidgets.QWidget()
        self.tab_headers.setObjectName("tab_headers")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_headers)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.text_headers = QtWidgets.QTextEdit(parent=self.tab_headers)
        self.text_headers.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_headers.setReadOnly(True)
        self.text_headers.setObjectName("text_headers")
        self.verticalLayout_10.addWidget(self.text_headers)
        self.tabWidget.addTab(self.tab_headers, "")
        self.tab_portscan = QtWidgets.QWidget()
        self.tab_portscan.setObjectName("tab_portscan")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_portscan)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.text_portscan = QtWidgets.QTextEdit(parent=self.tab_portscan)
        self.text_portscan.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_portscan.setReadOnly(True)
        self.text_portscan.setObjectName("text_portscan")
        self.verticalLayout_11.addWidget(self.text_portscan)
        self.tabWidget.addTab(self.tab_portscan, "")
        self.tab_reverse = QtWidgets.QWidget()
        self.tab_reverse.setObjectName("tab_reverse")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_reverse)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.text_reverse = QtWidgets.QTextEdit(parent=self.tab_reverse)
        self.text_reverse.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_reverse.setReadOnly(True)
        self.text_reverse.setObjectName("text_reverse")
        self.verticalLayout_12.addWidget(self.text_reverse)
        self.tabWidget.addTab(self.tab_reverse, "")
        self.tab_summary = QtWidgets.QWidget()
        self.tab_summary.setObjectName("tab_summary")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_summary)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.text_summary = QtWidgets.QTextEdit(parent=self.tab_summary)
        self.text_summary.setStyleSheet("QTextEdit {\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    background-color: transparent;\n"
"    color: #e8e8e8;\n"
"    border: none;\n"
"    padding: 20px;\n"
"    line-height: 1.5;\n"
"}")
        self.text_summary.setReadOnly(True)
        self.text_summary.setObjectName("text_summary")
        self.verticalLayout_13.addWidget(self.text_summary)
        self.tabWidget.addTab(self.tab_summary, "")
        self.resultsLayout.addWidget(self.tabWidget)
        self.mainLayout.addWidget(self.frame_results)
        self.label_creditos_2 = QtWidgets.QLabel(parent=self.centralwidget_2)
        self.label_creditos_2.setStyleSheet("font-size: 9pt;\n"
"color: #666666;\n"
"padding-top: 12px;\n"
"font-weight: 400;")
        self.label_creditos_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_creditos_2.setObjectName("label_creditos_2")
        self.mainLayout.addWidget(self.label_creditos_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExportar = QtGui.QAction(parent=MainWindow)
        self.actionExportar.setObjectName("actionExportar")
        self.actionGuardar = QtGui.QAction(parent=MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionConfiguracion = QtGui.QAction(parent=MainWindow)
        self.actionConfiguracion.setObjectName("actionConfiguracion")
        self.actionHistorial = QtGui.QAction(parent=MainWindow)
        self.actionHistorial.setObjectName("actionHistorial")
        self.actionAcerca_de = QtGui.QAction(parent=MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "OSINT - Herramienta de Análisis"))
        self.comboLanguage.setItemText(0, _translate("MainWindow", "🇪🇸 Español"))
        self.comboLanguage.setItemText(1, _translate("MainWindow", "🇺🇸 English"))
        self.label_legal.setText(_translate("MainWindow", "Esta herramienta es solo para fines educativos y auditorías autorizadas. Cumpla con todas las leyes y regulaciones locales."))
        self.label_instrucciones.setText(_translate("MainWindow", "Ingrese objetivo para análisis"))
        self.entrada_dominio.setPlaceholderText(_translate("MainWindow", "ejemplo.com | 8.8.8.8 | https://sitio.com"))
        self.btn_history.setToolTip(_translate("MainWindow", "Ver historial de análisis"))
        self.btn_history.setText(_translate("MainWindow", "⋮"))
        self.label_risk.setText(_translate("MainWindow", "Estado análisis:"))
        self.label_risk_text.setText(_translate("MainWindow", "• Inactivo"))
        self.btn_geo.setText(_translate("MainWindow", "🌍 Geolocalización"))
        self.btn_whois.setText(_translate("MainWindow", "📋 WHOIS"))
        self.btn_ping.setText(_translate("MainWindow", "📶 Ping/Traceroute"))
        self.btn_dns.setText(_translate("MainWindow", "🔍 DNS Lookup"))
        self.btn_ssl.setText(_translate("MainWindow", "🔐 SSL/TLS"))
        self.btn_headers.setText(_translate("MainWindow", "📄 Headers HTTP"))
        self.btn_portscan.setText(_translate("MainWindow", "🔎 Port Scan"))
        self.btn_reverse.setText(_translate("MainWindow", "🔄 Reverse IP"))
        self.btn_quick.setText(_translate("MainWindow", "🚀 Análisis Completo"))
        self.btn_export.setToolTip(_translate("MainWindow", "Exportar resultados (CSV, TXT, JSON)"))
        self.btn_export.setText(_translate("MainWindow", "📤 Exportar"))
        self.btn_clear.setToolTip(_translate("MainWindow", "Limpiar lista de objetivos"))
        self.btn_clear.setText(_translate("MainWindow", "🗑️ Limpiar lista"))
        self.label_results.setText(_translate("MainWindow", "📊 Resultados"))
        self.btn_copy.setToolTip(_translate("MainWindow", "Copiar resultados al portapapeles"))
        self.btn_copy.setText(_translate("MainWindow", "⎘"))
        self.btn_clear_results.setToolTip(_translate("MainWindow", "Limpiar todos los resultados"))
        self.btn_clear_results.setText(_translate("MainWindow", "×"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_geo), _translate("MainWindow", "🌍 Geoloc."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_whois), _translate("MainWindow", "📋 WHOIS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ping), _translate("MainWindow", "📶 Ping"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dns), _translate("MainWindow", "🔍 DNS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ssl), _translate("MainWindow", "🔐 SSL/TLS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_headers), _translate("MainWindow", "📄 Headers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_portscan), _translate("MainWindow", "🔎 Port Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reverse), _translate("MainWindow", "🔄 Reverse IP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_summary), _translate("MainWindow", "📋 Resumen"))
        self.label_creditos_2.setText(_translate("MainWindow", "OSINT Herramienta de Análisis • Desarrollado con fines académicos y librerías de código abierto"))
        self.actionExportar.setText(_translate("MainWindow", "&Exportar resultados..."))
        self.actionGuardar.setText(_translate("MainWindow", "&Guardar proyecto..."))
        self.actionSalir.setText(_translate("MainWindow", "&Salir"))
        self.actionConfiguracion.setText(_translate("MainWindow", "&Configuración..."))
        self.actionHistorial.setText(_translate("MainWindow", "&Historial de consultas"))
        self.actionAcerca_de.setText(_translate("MainWindow", "&Acerca de..."))
